### ISSUE TITLE
enable going to settings from plugins list

### ISSUE THREAD

**Issue by dickhardt** [hellocoop/wordpress#14]
<img width="349" alt="image" src="https://user-images.githubusercontent.com/688982/202240681-ba308a25-16f5-4ce0-b414-4a518961683b.png">

enable going to settings from plugins list

**Comment by mscurtescu** [comment]
Examples:

- https://developer.wordpress.org/reference/hooks/plugin_action_links_plugin_file/
- https://neliosoftware.com/blog/how-to-add-a-link-to-your-settings-in-the-wordpress-plugin-list/

**Comment by dickhardt** [comment]
I don't think this fix has been deployed yet 

![image](https://user-images.githubusercontent.com/688982/202947066-2fe2e7dc-ff50-4625-8f84-a451cc2be63e.png)

**Comment by mscurtescu** [comment]
It hasn't been released yet, but it is in the `main` branch.

**Comment by mscurtescu** [comment]
released
