### ISSUE TITLE
linking admin account does not link to admin account

### ISSUE THREAD

**Issue by dickhardt** [hellocoop/wordpress#19]
If the verified email from Hellō is different from email provided in creating WP install, then when linking the Hellō account a new user is created rather than linking to the admin account

=> we should update the email to be the email from Hellō 
=> if the Hellō account already is in WP - IE the user logged with Hellō separate from their admin account => I'm thinking we should delete the account that was already there and link the Hellō account to the admin account since that is what was wanted in linking accounts. Let's discuss if you have a different opinion.

**Comment by mscurtescu** [comment]
In `includes/hello-login-client-wrapper.php` see around line 555:
```php
$subject_identity = $client->get_subject_identity( $id_token_claim );
$user = $this->get_user_by_identity( $subject_identity );

// A pre-existing IDP mapped user wasn't found.
if ( ! $user ) {
	// If linking existing users or creating new ones call the `create_new_user` method which handles both cases.
	if ( $this->settings->link_existing_users || $this->settings->create_if_does_not_exist ) {
		$user = $this->create_new_user( $subject_identity, $user_claim );
		if ( is_wp_error( $user ) ) {
			$this->error_redirect( $user );
		}
	} else {
		$this->error_redirect( new WP_Error( 'identity-not-map-existing-user', __( 'User identity is not linked to an existing WordPress user.', 'hello-login' ), $user_claim ) );
	}
}
```
