### ISSUE TITLE
Update user profile information with contents of ID Token

### ISSUE THREAD

**Issue by dickhardt** [hellocoop/wordpress#28]
Do we only fill in missing information in user profile when linking Hellō wallet to existing account, or do we update the user profile with the ID Token?

@mscurtescu what happens now?

**Comment by mscurtescu** [comment]
When linking currently no attributes (other than the Hello user id) are updated on the user object.

**Comment by mscurtescu** [comment]
First and last name are updated on sign-in, only if not set.

https://github.com/hellocoop/wordpress/commit/86b8c01f43743db025f3f7f2da1b22104727ec5b
