### ISSUE TITLE
authentication request should be generated on button click

### ISSUE THREAD

**Issue by mscurtescu** [hellocoop/wordpress#29]
**Describe the bug**

"Connect with Hellō" and "Link with Hellō" buttons generate the authentication request URL when the page is rendered. This URL has `state` and `nonce` parameters that have a short expiration time in the WordPress transient storage

**To Reproduce**

1. Go to ''Hellō Login" plugin settings page
1. Notice the "Link with Hellō" button at the to
    1. If the plugin is not configured then go through Quickstart first
1. Wait for at least 3 minutes
1. Click on 'Link with Hellō'
1. Go through with Hellō interaction
1. When sent back to WordPress notice the "Invalid state" error on the wp-login.php page.

**Screenshots**
![invalid-state](https://user-images.githubusercontent.com/942078/203873188-6388e75c-5438-436a-a922-8d2ba1436cf6.png)

**Expected behavior**
Sing-in or account linking should work no matter when a page was rendered (as long as there is still an active session).

**Comment by dickhardt** [comment]
In the wallet code we make an API call to get the redirect uri on button click
