### ISSUE TITLE
Login page layout fixes

### ISSUE THREAD

**Issue by dickhardt** [hellocoop/wordpress#67]
Move notification (A) to (B)
Move (C) to be inside [ Continue with username or email ] collapsable box

![image](https://user-images.githubusercontent.com/688982/206531021-aca4b561-008f-4bde-86f6-40cc270409dc.png)

**Comment by mscurtescu** [comment]
(A) to (B) move solved, not in a generic way, only for the logout page, but so far that's the only case when this problem showed up.

![loggedout](https://user-images.githubusercontent.com/942078/206574716-8f3326e7-7979-4dd1-8ac6-720dd3499079.png)
