### ISSUE TITLE
Link / unlink wallet from Profile page

### ISSUE THREAD

**Issue by dickhardt** [hellocoop/wordpress#68]
Enable users to link and unlink their Hellō Wallet from their profile page

If wallet is not linked

![image](https://user-images.githubusercontent.com/688982/206533439-2cc51ce5-141a-4f21-b51d-bf773040a11d.png)

If wallet is linked (regular button similar to [ Set New Password ] to unlink

![image](https://user-images.githubusercontent.com/688982/206533291-25ab08e5-1330-45f6-99b6-14388c3f53ea.png)

**Comment by mscurtescu** [comment]
The only profile page filter found so far is for adding contact methods under the Contact Info section. This only allows input fields of type text.

See:

- https://developer.wordpress.org/reference/hooks/user_contactmethods/
- https://www.presstigers.com/using-wordpress-filter-to-add-custom-fields-in-user-profile/

The code that added the field in the screenshot:
```php
add_filter( 'user_contactmethods', array( $plugin, 'add_contact_methods' ), 1 );
```
and
```php
public function add_contact_methods( $methods ) {
	$methods['hello'] = "Hellō Wallet";
	return $methods;
}
```
![contact_methods](https://user-images.githubusercontent.com/942078/206640210-a276dc46-e4f2-487d-83bc-e010b4ec6154.png)
